# Site settings
baseURL = "."
relativeURLs = true
uglyURLs = true
languageCode = "en-us"
title = "Kleartrace"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Kleartrace Admin"
  description = "Bringing clarity to the global food supply chain!"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Kleartrace"
    menu = "Menu"
    # Optional logo as brand stored in img/
   #  logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Solution"
      url = "solution.html"

    [[params.navigation.links]]
      name = "About us"
      url = "aboutus.html"

    [[params.navigation.links]]
      name = "Resources"
      url = "resources.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Request Free Trial"
      url = "https://docs.google.com/forms/d/e/1FAIpQLSf9922EuNVw29f-VJqOpeq5k5HOYdLGo0QWRuoPiqYmIidLQA/viewform"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Sign In"
      url = "http://app.kleartrace.com/"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, we are Kleatrace!"
    subtitle = "Your solution to improved traceability, FSMA compliance and reduced spoilage in the food and drug supply chain"
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Simple sleek device"
      subtitle = "Can fit into any package"
      image = "pic01.jpg"
      url = "solution.html"

    [[params.tiles.showcase]]
      title = "Free your data"
      subtitle = "Reliable cloud based solution"
      image = "pic02.jpg"
      url = "aboutus.html"

    [[params.tiles.showcase]]
      title = "Real-time Tracking"
      subtitle = "Robust communication infrastructure"
      image = "pic03.jpg"
      url = "#"

    [[params.tiles.showcase]]
      title = "Freshness is our priority"
      subtitle = "Keeping fressness and safety intact"
      image = "pic04.jpg"
      url = "#"

    [[params.tiles.showcase]]
      title = "FSMA Compliant"
      subtitle = "One-stop system soltion for your compliance and reporting needs"
      image = "pic05.jpg"
      url = "#"

    [[params.tiles.showcase]]
      title = "Simple User interface and accesibility"
      subtitle = "Available 24x7 from mobile, web or desptop"
      image = "pic06.jpg"
      url = "#"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "The new generation of food safety is here"
    subtitle = """Cutting edge technology solutions that you can rely on for your most important shipments.
    Alert systems, and monitoring systems that work for you and with you. User Interface that delights on the web and on the mobile"""
    buttonText = "Request  a Free Trial"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSf9922EuNVw29f-VJqOpeq5k5HOYdLGo0QWRuoPiqYmIidLQA/viewform"


  # Contact section
  [params.contact]
    enable = true
    #buttonSend = "Send message"
    #buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "info@kleartrace.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000)000-0000"

    [[params.contact.address]]
    title = "Kleartrace LLC"
    street = "1911 Shadow Branch Lane"
    city = "Houston, TX 77077"
    country = "United States of America"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Kleartrace LLC"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"


